package com.nuance.speechkitsample;

import android.net.Uri;

import com.nuance.speechkit.PcmFormat;

/**
 * All Nuance Developers configuration parameters can be set here.
 *
 * Copyright (c) 2015 Nuance Communications. All rights reserved.
 */
public class Configuration {

    //All fields are required.
    //Your credentials can be found in your Nuance Developers portal, under "Manage My Apps".
    public static final String APP_KEY = "636d4bf5f37fbe3f15973927dcffa089035d98d38e138499898896b4a7efb50a5c00ff4f7fbd8e9554c8bc30c75db9cbba519e486522e2eeab78a25267575cc4";
    public static final String APP_ID = "NMDPTRIAL_thecharleslagace_gmail_com20170128144042";
    public static final String SERVER_HOST = "nmsps.dev.nuance.com";
    public static final String SERVER_PORT = "443";

    public static final String LANGUAGE = "eng-USA";

    public static final Uri SERVER_URI = Uri.parse("nmsps://" + APP_ID + "@" + SERVER_HOST + ":" + SERVER_PORT);

    //Only needed if using NLU
    public static final String CONTEXT_TAG = "M5037_A2337";

    public static final PcmFormat PCM_FORMAT = new PcmFormat(PcmFormat.SampleFormat.SignedLinear16, 16000, 1);
    public static final String LANGUAGE_CODE = (Configuration.LANGUAGE.contains("!") ? "eng-USA" : Configuration.LANGUAGE);

    public static final String [] PROGRAM_NAMES = {
            "accounting",
            "african studies",
            "agribusiness",
            "agribusiness entrepreneurship",
            "agricultural economics",
            "agricultural production",
            "agro environmental sciences",
            "anatomy and cell biology",
            "animal biology",
            "animal health and disease",
            "animal production",
            "anthropology 0",
            "applied ecology",
            "applied mathematics",
            "applied mathematics faculty arts",
            "arabic language",
            "architecture pre professional",
            "art history",
            "arts minor faculty engineering",
            "atmospheric environment and air quality",
            "atmospheric science and physics",
            "atmospheric sciences",
            "behavioural science",
            "biochemistry",
            "biodiversity and conservation",
            "bioengineering",
            "biology",
            "biology and mathematics",
            "biomedical engineering",
            "bioresource engineering faculty agricultural environmental sciences",
            "bioresource engineering professional agrology option faculty agricultural environmental sciences",
            "biotechnology faculty engineering",
            "biotechnology faculty science",
            "canadian ethnic and racial studies",
            "canadian studies",
            "catholic studies",
            "chemical engineering",
            "chemical engineering faculty science",
            "chemistry",
            "chemistry faculty engineering",
            "civil engineering",
            "classics",
            "cognitive science",
            "communication studies",
            "composition",
            "computer engineering",
            "computer science faculty arts",
            "computer science faculty engineering",
            "computer science faculty science",
            "computer science and biology",
            "construction engineering and marketing",
            "dentistry",
            "dietetics professional program",
            "earth and planetary sciences",
            "earth sciences",
            "earth sciences and economics",
            "earth system science",
            "east asian cultural studies",
            "east asian language supplementary",
            "east asian language and literature",
            "east asian studies",
            "ecological agriculture",
            "ecological determinants health",
            "ecological determinants health society",
            "economics desautels faculty management",
            "economics faculty arts",
            "economics faculty engineering",
            "economics and accounting faculty arts",
            "economics and finance desautels faculty management",
            "economics and finance faculty arts",
            "economics and earths environment",
            "education arts students",
            "education science students",
            "educational psychology",
            "electrical engineering faculty engineering",
            "electrical engineering faculty science",
            "english cultural studies",
            "english drama and theatre",
            "english literature",
            "entrepreneurship desautels faculty management",
            "entrepreneurship science students faculty science",
            "environment bachelor arts and science",
            "environment diploma",
            "environment faculty agricultural and environmental sciences macdonald campus",
            "environment faculty arts",
            "environment faculty engineering",
            "environment faculty science",
            "environment and development",
            "environmental biology",
            "environmental economics",
            "environmental engineering faculty agricultural and environmental sciences",
            "environmental engineering faculty engineering",
            "environmetrics",
            "european literature and culture",
            "farm management and technology",
            "field studies",
            "finance",
            "finance non management students 0",
            "food production and environment",
            "food science",
            "food science nutritional science",
            "gender sexuality feminist and social justice studies",
            "general engineering program suspended",
            "general science",
            "geochemistry",
            "geographic information systems",
            "geographic information systems and remote sensing",
            "geography faculty arts",
            "geography faculty science",
            "geography urban systems faculty arts",
            "geology faculty science",
            "german language",
            "german studies",
            "german studies literature and culture",
            "global food security",
            "health geography",
            "hispanic studies",
            "hispanic studies languages",
            "hispanic studies literature and culture",
            "history",
            "history and philosophy science",
            "human nutrition",
            "immunology",
            "indigenous studies",
            "industrial relations",
            "information systems",
            "information systems digital innovation",
            "information systems it business",
            "interdisciplinary life sciences",
            "international agriculture",
            "international business",
            "international development studies 0",
            "international management",
            "investment management",
            "italian studies",
            "jewish law",
            "jewish studies",
            "kindergarten and elementary education",
            "kindergarten and elementary education first nations and inuit studies",
            "kindergarten and elementary education jewish studies",
            "kindergarten and elementary education pedagogie de limmersion francaise 0",
            "kinesiology",
            "kinesiology science students",
            "labour management relations and human resources",
            "land surface processes and environmental change",
            "langue et litterature francaises langue francaise",
            "langue et litterature francaises langue francaise et traduction",
            "langue et litterature francaises etudies et pratiques litteraire",
            "langue et litterature francaises traduction",
            "latin american and caribbean studies",
            "latin american studies",
            "law",
            "liberal arts",
            "life sciences 0",
            "life sciences multidisciplinary",
            "linguistics",
            "management non management students",
            "managing sustainability",
            "marketing",
            "marketing non management students",
            "materials engineering co op",
            "mathematics desautels faculty management",
            "mathematics faculty arts",
            "mathematics faculty engineering",
            "mathematics faculty science",
            "mathematics and computer science faculty arts",
            "mathematics and computer science faculty science",
            "mathematics and physics",
            "mechanical engineering",
            "mechanical engineering aeronautical engineering concentration",
            "mechanical engineering design concentration",
            "medicine",
            "medieval studies",
            "meteorology diploma",
            "microbiology and immunology",
            "microbiology and molecular biotechnology",
            "mining engineering co op",
            "music faculty arts",
            "music education",
            "music education professional program",
            "music entrepreneurship schulich school music",
            "music faculty program",
            "music faculty program jazz",
            "music history",
            "music performance jazz",
            "music performance licentiate music",
            "music performance orchestral instruments",
            "music performance organ harpsichord guitar",
            "music performance piano",
            "music performance voice",
            "music performance early music instruments",
            "music performance early music voice",
            "music theory",
            "musical applications technology",
            "musical science and technology",
            "nanotechnology",
            "natural history",
            "neo hellenic studies",
            "neuroscience",
            "north american studies",
            "nursing",
            "nursing integrated",
            "nutrition",
            "occupational therapy",
            "operations management non management students",
            "organizational behaviour",
            "persian language",
            "pharmacology",
            "philosophy",
            "physical and health education",
            "physical therapy",
            "physics faculty engineering",
            "physics faculty science",
            "physics and chemistry",
            "physics and computer science",
            "physics and geophysics",
            "physiology",
            "physiology and mathematics",
            "physiology and physics",
            "planetary sciences",
            "plant biology",
            "plant production",
            "political science",
            "probability and statistics faculty science",
            "probability and statisticsfaculty arts",
            "professional agrology",
            "psychology faculty arts",
            "psychology faculty science",
            "quebec studies",
            "religion and globalization",
            "religious studies bachelor theology 0",
            "religious studies asian religions faculty arts",
            "religious studies western religions faculty arts",
            "renewable resource management",
            "russian",
            "russian culture",
            "science arts students",
            "scriptural languages",
            "scriptures and interpretations faculty arts",
            "secondary education english",
            "secondary education mathematics",
            "secondary education science and technology",
            "secondary education social sciences",
            "social entrepreneurship faculty arts",
            "social studies medicine",
            "social work",
            "sociology",
            "software engineering faculty arts",
            "software engineering faculty engineering",
            "software engineering faculty science",
            "soil and water resources",
            "statistics desautels faculty management",
            "statistics faculty arts",
            "statistics faculty science",
            "statistics and computer science",
            "strategic management",
            "strategic management global strategy",
            "strategic management social business enterprise",
            "sustainability science and society",
            "teaching english second language tesl",
            "teaching english second language tesl greek option",
            "technological entrepreneurship engineering",
            "turkish language",
            "urdu language",
            "water environments and ecosystems",
            "wildlife biology",
            "world cinemas",
            "world islamic middle east studies",
            "world religions faculty arts",
    };
    public static final String [] PROGRAM_URL =
    {
        "https://www.mcgill.ca/undergraduate-admissions/accounting",
                "https://www.mcgill.ca/undergraduate-admissions/african-studies",
                "https://www.mcgill.ca/undergraduate-admissions/agribusiness",
                "https://www.mcgill.ca/undergraduate-admissions/agribusiness-entrepreneurship",
                "https://www.mcgill.ca/undergraduate-admissions/agricultural-economics",
                "https://www.mcgill.ca/undergraduate-admissions/agricultural-production",
                "https://www.mcgill.ca/undergraduate-admissions/agro-environmental-sciences",
                "https://www.mcgill.ca/undergraduate-admissions/anatomy-and-cell-biology",
                "https://www.mcgill.ca/undergraduate-admissions/animal-biology",
                "https://www.mcgill.ca/undergraduate-admissions/animal-health-and-disease",
                "https://www.mcgill.ca/undergraduate-admissions/animal-production",
                "https://www.mcgill.ca/undergraduate-admissions/anthropology-0",
                "https://www.mcgill.ca/undergraduate-admissions/applied-ecology",
                "https://www.mcgill.ca/undergraduate-admissions/applied-mathematics",
                "https://www.mcgill.ca/undergraduate-admissions/applied-mathematics-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/arabic-language",
                "https://www.mcgill.ca/undergraduate-admissions/architecture-pre-professional",
                "https://www.mcgill.ca/undergraduate-admissions/art-history",
                "https://www.mcgill.ca/undergraduate-admissions/arts-minor-faculty-engineering",
                "https://www.mcgill.ca/undergraduate-admissions/atmospheric-environment-and-air-quality",
                "https://www.mcgill.ca/undergraduate-admissions/atmospheric-science-and-physics",
                "https://www.mcgill.ca/undergraduate-admissions/atmospheric-sciences",
                "https://www.mcgill.ca/undergraduate-admissions/behavioural-science",
                "https://www.mcgill.ca/undergraduate-admissions/biochemistry",
                "https://www.mcgill.ca/undergraduate-admissions/biodiversity-and-conservation",
                "https://www.mcgill.ca/undergraduate-admissions/bioengineering",
                "https://www.mcgill.ca/undergraduate-admissions/biology",
                "https://www.mcgill.ca/undergraduate-admissions/biology-and-mathematics",
                "https://www.mcgill.ca/undergraduate-admissions/biomedical-engineering",
                "https://www.mcgill.ca/undergraduate-admissions/bioresource-engineering-faculty-agricultural-environmental-sciences",
                "https://www.mcgill.ca/undergraduate-admissions/bioresource-engineering-professional-agrology-option-faculty-agricultural-environmental-sciences",
                "https://www.mcgill.ca/undergraduate-admissions/biotechnology-faculty-engineering",
                "https://www.mcgill.ca/undergraduate-admissions/biotechnology-faculty-science",
                "https://www.mcgill.ca/undergraduate-admissions/canadian-ethnic-and-racial-studies",
                "https://www.mcgill.ca/undergraduate-admissions/canadian-studies",
                "https://www.mcgill.ca/undergraduate-admissions/catholic-studies",
                "https://www.mcgill.ca/undergraduate-admissions/chemical-engineering",
                "https://www.mcgill.ca/undergraduate-admissions/chemical-engineering-faculty-science",
                "https://www.mcgill.ca/undergraduate-admissions/chemistry",
                "https://www.mcgill.ca/undergraduate-admissions/chemistry-faculty-engineering",
                "https://www.mcgill.ca/undergraduate-admissions/civil-engineering",
                "https://www.mcgill.ca/undergraduate-admissions/classics",
                "https://www.mcgill.ca/undergraduate-admissions/cognitive-science",
                "https://www.mcgill.ca/undergraduate-admissions/communication-studies",
                "https://www.mcgill.ca/undergraduate-admissions/composition",
                "https://www.mcgill.ca/undergraduate-admissions/computer-engineering",
                "https://www.mcgill.ca/undergraduate-admissions/computer-science-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/computer-science-faculty-engineering",
                "https://www.mcgill.ca/undergraduate-admissions/computer-science-faculty-science",
                "https://www.mcgill.ca/undergraduate-admissions/computer-science-and-biology",
                "https://www.mcgill.ca/undergraduate-admissions/construction-engineering-and-marketing",
                "https://www.mcgill.ca/undergraduate-admissions/dentistry",
                "https://www.mcgill.ca/undergraduate-admissions/dietetics-professional-program",
                "https://www.mcgill.ca/undergraduate-admissions/earth-and-planetary-sciences",
                "https://www.mcgill.ca/undergraduate-admissions/earth-sciences",
                "https://www.mcgill.ca/undergraduate-admissions/earth-sciences-and-economics",
                "https://www.mcgill.ca/undergraduate-admissions/earth-system-science",
                "https://www.mcgill.ca/undergraduate-admissions/east-asian-cultural-studies",
                "https://www.mcgill.ca/undergraduate-admissions/east-asian-language-supplementary",
                "https://www.mcgill.ca/undergraduate-admissions/east-asian-language-and-literature",
                "https://www.mcgill.ca/undergraduate-admissions/east-asian-studies",
                "https://www.mcgill.ca/undergraduate-admissions/ecological-agriculture",
                "https://www.mcgill.ca/undergraduate-admissions/ecological-determinants-health",
                "https://www.mcgill.ca/undergraduate-admissions/ecological-determinants-health-society",
                "https://www.mcgill.ca/undergraduate-admissions/economics-desautels-faculty-management",
                "https://www.mcgill.ca/undergraduate-admissions/economics-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/economics-faculty-engineering",
                "https://www.mcgill.ca/undergraduate-admissions/economics-and-accounting-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/economics-and-finance-desautels-faculty-management",
                "https://www.mcgill.ca/undergraduate-admissions/economics-and-finance-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/economics-and-earths-environment",
                "https://www.mcgill.ca/undergraduate-admissions/education-arts-students",
                "https://www.mcgill.ca/undergraduate-admissions/education-science-students",
                "https://www.mcgill.ca/undergraduate-admissions/educational-psychology",
                "https://www.mcgill.ca/undergraduate-admissions/electrical-engineering-faculty-engineering",
                "https://www.mcgill.ca/undergraduate-admissions/electrical-engineering-faculty-science",
                "https://www.mcgill.ca/undergraduate-admissions/english-cultural-studies",
                "https://www.mcgill.ca/undergraduate-admissions/english-drama-and-theatre",
                "https://www.mcgill.ca/undergraduate-admissions/english-literature",
                "https://www.mcgill.ca/undergraduate-admissions/entrepreneurship-desautels-faculty-management",
                "https://www.mcgill.ca/undergraduate-admissions/entrepreneurship-science-students-faculty-science",
                "https://www.mcgill.ca/undergraduate-admissions/environment-bachelor-arts-and-science",
                "https://www.mcgill.ca/undergraduate-admissions/environment-diploma",
                "https://www.mcgill.ca/undergraduate-admissions/environment-faculty-agricultural-and-environmental-sciences-macdonald-campus",
                "https://www.mcgill.ca/undergraduate-admissions/environment-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/environment-faculty-engineering",
                "https://www.mcgill.ca/undergraduate-admissions/environment-faculty-science",
                "https://www.mcgill.ca/undergraduate-admissions/environment-and-development",
                "https://www.mcgill.ca/undergraduate-admissions/environmental-biology",
                "https://www.mcgill.ca/undergraduate-admissions/environmental-economics",
                "https://www.mcgill.ca/undergraduate-admissions/environmental-engineering-faculty-agricultural-and-environmental-sciences",
                "https://www.mcgill.ca/undergraduate-admissions/environmental-engineering-faculty-engineering",
                "https://www.mcgill.ca/undergraduate-admissions/environmetrics",
                "https://www.mcgill.ca/undergraduate-admissions/european-literature-and-culture",
                "https://www.mcgill.ca/undergraduate-admissions/farm-management-and-technology",
                "https://www.mcgill.ca/undergraduate-admissions/field-studies",
                "https://www.mcgill.ca/undergraduate-admissions/finance",
                "https://www.mcgill.ca/undergraduate-admissions/finance-non-management-students-0",
                "https://www.mcgill.ca/undergraduate-admissions/food-production-and-environment",
                "https://www.mcgill.ca/undergraduate-admissions/food-science",
                "https://www.mcgill.ca/undergraduate-admissions/food-science-nutritional-science",
                "https://www.mcgill.ca/undergraduate-admissions/gender-sexuality-feminist-and-social-justice-studies",
                "https://www.mcgill.ca/undergraduate-admissions/general-engineering-program-suspended",
                "https://www.mcgill.ca/undergraduate-admissions/general-science",
                "https://www.mcgill.ca/undergraduate-admissions/geochemistry",
                "https://www.mcgill.ca/undergraduate-admissions/geographic-information-systems",
                "https://www.mcgill.ca/undergraduate-admissions/geographic-information-systems-and-remote-sensing",
                "https://www.mcgill.ca/undergraduate-admissions/geography-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/geography-faculty-science",
                "https://www.mcgill.ca/undergraduate-admissions/geography-urban-systems-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/geology-faculty-science",
                "https://www.mcgill.ca/undergraduate-admissions/german-language",
                "https://www.mcgill.ca/undergraduate-admissions/german-studies",
                "https://www.mcgill.ca/undergraduate-admissions/german-studies-literature-and-culture",
                "https://www.mcgill.ca/undergraduate-admissions/global-food-security",
                "https://www.mcgill.ca/undergraduate-admissions/health-geography",
                "https://www.mcgill.ca/undergraduate-admissions/hispanic-studies",
                "https://www.mcgill.ca/undergraduate-admissions/hispanic-studies-languages",
                "https://www.mcgill.ca/undergraduate-admissions/hispanic-studies-literature-and-culture",
                "https://www.mcgill.ca/undergraduate-admissions/history",
                "https://www.mcgill.ca/undergraduate-admissions/history-and-philosophy-science",
                "https://www.mcgill.ca/undergraduate-admissions/human-nutrition",
                "https://www.mcgill.ca/undergraduate-admissions/immunology",
                "https://www.mcgill.ca/undergraduate-admissions/indigenous-studies",
                "https://www.mcgill.ca/undergraduate-admissions/industrial-relations",
                "https://www.mcgill.ca/undergraduate-admissions/information-systems",
                "https://www.mcgill.ca/undergraduate-admissions/information-systems-digital-innovation",
                "https://www.mcgill.ca/undergraduate-admissions/information-systems-it-business",
                "https://www.mcgill.ca/undergraduate-admissions/interdisciplinary-life-sciences",
                "https://www.mcgill.ca/undergraduate-admissions/international-agriculture",
                "https://www.mcgill.ca/undergraduate-admissions/international-business",
                "https://www.mcgill.ca/undergraduate-admissions/international-development-studies-0",
                "https://www.mcgill.ca/undergraduate-admissions/international-management",
                "https://www.mcgill.ca/undergraduate-admissions/investment-management",
                "https://www.mcgill.ca/undergraduate-admissions/italian-studies",
                "https://www.mcgill.ca/undergraduate-admissions/jewish-law",
                "https://www.mcgill.ca/undergraduate-admissions/jewish-studies",
                "https://www.mcgill.ca/undergraduate-admissions/kindergarten-and-elementary-education",
                "https://www.mcgill.ca/undergraduate-admissions/kindergarten-and-elementary-education-first-nations-and-inuit-studies",
                "https://www.mcgill.ca/undergraduate-admissions/kindergarten-and-elementary-education-jewish-studies",
                "https://www.mcgill.ca/undergraduate-admissions/kindergarten-and-elementary-education-pedagogie-de-limmersion-francaise-0",
                "https://www.mcgill.ca/undergraduate-admissions/kinesiology",
                "https://www.mcgill.ca/undergraduate-admissions/kinesiology-science-students",
                "https://www.mcgill.ca/undergraduate-admissions/labour-management-relations-and-human-resources",
                "https://www.mcgill.ca/undergraduate-admissions/land-surface-processes-and-environmental-change",
                "https://www.mcgill.ca/undergraduate-admissions/langue-et-litterature-francaises-langue-francaise",
                "https://www.mcgill.ca/undergraduate-admissions/langue-et-litterature-francaises-langue-francaise-et-traduction",
                "https://www.mcgill.ca/undergraduate-admissions/langue-et-litterature-francaises-etudies-et-pratiques-litteraire",
                "https://www.mcgill.ca/undergraduate-admissions/langue-et-litterature-francaises-traduction",
                "https://www.mcgill.ca/undergraduate-admissions/latin-american-and-caribbean-studies",
                "https://www.mcgill.ca/undergraduate-admissions/latin-american-studies",
                "https://www.mcgill.ca/undergraduate-admissions/law",
                "https://www.mcgill.ca/undergraduate-admissions/liberal-arts",
                "https://www.mcgill.ca/undergraduate-admissions/life-sciences-0",
                "https://www.mcgill.ca/undergraduate-admissions/life-sciences-multidisciplinary",
                "https://www.mcgill.ca/undergraduate-admissions/linguistics",
                "https://www.mcgill.ca/undergraduate-admissions/management-non-management-students",
                "https://www.mcgill.ca/undergraduate-admissions/managing-sustainability",
                "https://www.mcgill.ca/undergraduate-admissions/marketing",
                "https://www.mcgill.ca/undergraduate-admissions/marketing-non-management-students",
                "https://www.mcgill.ca/undergraduate-admissions/materials-engineering-co-op",
                "https://www.mcgill.ca/undergraduate-admissions/mathematics-desautels-faculty-management",
                "https://www.mcgill.ca/undergraduate-admissions/mathematics-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/mathematics-faculty-engineering",
                "https://www.mcgill.ca/undergraduate-admissions/mathematics-faculty-science",
                "https://www.mcgill.ca/undergraduate-admissions/mathematics-and-computer-science-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/mathematics-and-computer-science-faculty-science",
                "https://www.mcgill.ca/undergraduate-admissions/mathematics-and-physics",
                "https://www.mcgill.ca/undergraduate-admissions/mechanical-engineering",
                "https://www.mcgill.ca/undergraduate-admissions/mechanical-engineering-aeronautical-engineering-concentration",
                "https://www.mcgill.ca/undergraduate-admissions/mechanical-engineering-design-concentration",
                "https://www.mcgill.ca/undergraduate-admissions/medicine",
                "https://www.mcgill.ca/undergraduate-admissions/medieval-studies",
                "https://www.mcgill.ca/undergraduate-admissions/meteorology-diploma",
                "https://www.mcgill.ca/undergraduate-admissions/microbiology-and-immunology",
                "https://www.mcgill.ca/undergraduate-admissions/microbiology-and-molecular-biotechnology",
                "https://www.mcgill.ca/undergraduate-admissions/mining-engineering-co-op",
                "https://www.mcgill.ca/undergraduate-admissions/music-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/music-education",
                "https://www.mcgill.ca/undergraduate-admissions/music-education-professional-program",
                "https://www.mcgill.ca/undergraduate-admissions/music-entrepreneurship-schulich-school-music",
                "https://www.mcgill.ca/undergraduate-admissions/music-faculty-program",
                "https://www.mcgill.ca/undergraduate-admissions/music-faculty-program-jazz",
                "https://www.mcgill.ca/undergraduate-admissions/music-history",
                "https://www.mcgill.ca/undergraduate-admissions/music-performance-jazz",
                "https://www.mcgill.ca/undergraduate-admissions/music-performance-licentiate-music",
                "https://www.mcgill.ca/undergraduate-admissions/music-performance-orchestral-instruments",
                "https://www.mcgill.ca/undergraduate-admissions/music-performance-organ-harpsichord-guitar",
                "https://www.mcgill.ca/undergraduate-admissions/music-performance-piano",
                "https://www.mcgill.ca/undergraduate-admissions/music-performance-voice",
                "https://www.mcgill.ca/undergraduate-admissions/music-performance-early-music-instruments",
                "https://www.mcgill.ca/undergraduate-admissions/music-performance-early-music-voice",
                "https://www.mcgill.ca/undergraduate-admissions/music-theory",
                "https://www.mcgill.ca/undergraduate-admissions/musical-applications-technology",
                "https://www.mcgill.ca/undergraduate-admissions/musical-science-and-technology",
                "https://www.mcgill.ca/undergraduate-admissions/nanotechnology",
                "https://www.mcgill.ca/undergraduate-admissions/natural-history",
                "https://www.mcgill.ca/undergraduate-admissions/neo-hellenic-studies",
                "https://www.mcgill.ca/undergraduate-admissions/neuroscience",
                "https://www.mcgill.ca/undergraduate-admissions/north-american-studies",
                "https://www.mcgill.ca/undergraduate-admissions/nursing",
                "https://www.mcgill.ca/undergraduate-admissions/nursing-integrated",
                "https://www.mcgill.ca/undergraduate-admissions/nutrition",
                "https://www.mcgill.ca/undergraduate-admissions/occupational-therapy",
                "https://www.mcgill.ca/undergraduate-admissions/operations-management-non-management-students",
                "https://www.mcgill.ca/undergraduate-admissions/organizational-behaviour",
                "https://www.mcgill.ca/undergraduate-admissions/persian-language",
                "https://www.mcgill.ca/undergraduate-admissions/pharmacology",
                "https://www.mcgill.ca/undergraduate-admissions/philosophy",
                "https://www.mcgill.ca/undergraduate-admissions/physical-and-health-education",
                "https://www.mcgill.ca/undergraduate-admissions/physical-therapy",
                "https://www.mcgill.ca/undergraduate-admissions/physics-faculty-engineering",
                "https://www.mcgill.ca/undergraduate-admissions/physics-faculty-science",
                "https://www.mcgill.ca/undergraduate-admissions/physics-and-chemistry",
                "https://www.mcgill.ca/undergraduate-admissions/physics-and-computer-science",
                "https://www.mcgill.ca/undergraduate-admissions/physics-and-geophysics",
                "https://www.mcgill.ca/undergraduate-admissions/physiology",
                "https://www.mcgill.ca/undergraduate-admissions/physiology-and-mathematics",
                "https://www.mcgill.ca/undergraduate-admissions/physiology-and-physics",
                "https://www.mcgill.ca/undergraduate-admissions/planetary-sciences",
                "https://www.mcgill.ca/undergraduate-admissions/plant-biology",
                "https://www.mcgill.ca/undergraduate-admissions/plant-production",
                "https://www.mcgill.ca/undergraduate-admissions/political-science",
                "https://www.mcgill.ca/undergraduate-admissions/probability-and-statistics-faculty-science",
                "https://www.mcgill.ca/undergraduate-admissions/probability-and-statisticsfaculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/professional-agrology",
                "https://www.mcgill.ca/undergraduate-admissions/psychology-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/psychology-faculty-science",
                "https://www.mcgill.ca/undergraduate-admissions/quebec-studies",
                "https://www.mcgill.ca/undergraduate-admissions/religion-and-globalization",
                "https://www.mcgill.ca/undergraduate-admissions/religious-studies-bachelor-theology-0",
                "https://www.mcgill.ca/undergraduate-admissions/religious-studies-asian-religions-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/religious-studies-western-religions-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/renewable-resource-management",
                "https://www.mcgill.ca/undergraduate-admissions/russian",
                "https://www.mcgill.ca/undergraduate-admissions/russian-culture",
                "https://www.mcgill.ca/undergraduate-admissions/science-arts-students",
                "https://www.mcgill.ca/undergraduate-admissions/scriptural-languages",
                "https://www.mcgill.ca/undergraduate-admissions/scriptures-and-interpretations-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/secondary-education-english",
                "https://www.mcgill.ca/undergraduate-admissions/secondary-education-mathematics",
                "https://www.mcgill.ca/undergraduate-admissions/secondary-education-science-and-technology",
                "https://www.mcgill.ca/undergraduate-admissions/secondary-education-social-sciences",
                "https://www.mcgill.ca/undergraduate-admissions/social-entrepreneurship-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/social-studies-medicine",
                "https://www.mcgill.ca/undergraduate-admissions/social-work",
                "https://www.mcgill.ca/undergraduate-admissions/sociology",
                "https://www.mcgill.ca/undergraduate-admissions/software-engineering-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/software-engineering-faculty-engineering",
                "https://www.mcgill.ca/undergraduate-admissions/software-engineering-faculty-science",
                "https://www.mcgill.ca/undergraduate-admissions/soil-and-water-resources",
                "https://www.mcgill.ca/undergraduate-admissions/statistics-desautels-faculty-management",
                "https://www.mcgill.ca/undergraduate-admissions/statistics-faculty-arts",
                "https://www.mcgill.ca/undergraduate-admissions/statistics-faculty-science",
                "https://www.mcgill.ca/undergraduate-admissions/statistics-and-computer-science",
                "https://www.mcgill.ca/undergraduate-admissions/strategic-management",
                "https://www.mcgill.ca/undergraduate-admissions/strategic-management-global-strategy",
                "https://www.mcgill.ca/undergraduate-admissions/strategic-management-social-business-enterprise",
                "https://www.mcgill.ca/undergraduate-admissions/sustainability-science-and-society",
                "https://www.mcgill.ca/undergraduate-admissions/teaching-english-second-language-tesl",
                "https://www.mcgill.ca/undergraduate-admissions/teaching-english-second-language-tesl-greek-option",
                "https://www.mcgill.ca/undergraduate-admissions/technological-entrepreneurship-engineering",
                "https://www.mcgill.ca/undergraduate-admissions/turkish-language",
                "https://www.mcgill.ca/undergraduate-admissions/urdu-language",
                "https://www.mcgill.ca/undergraduate-admissions/water-environments-and-ecosystems",
                "https://www.mcgill.ca/undergraduate-admissions/wildlife-biology",
                "https://www.mcgill.ca/undergraduate-admissions/world-cinemas",
                "https://www.mcgill.ca/undergraduate-admissions/world-islamic-middle-east-studies",
                "https://www.mcgill.ca/undergraduate-admissions/world-religions-faculty-arts",
    };

}



